export const EXPLANATION_LIST_REQUEST = "EXPLANATION_LIST_REQUEST";
export const EXPLANATION_LIST_SUCCESS = "EXPLANATION_LIST_SUCCESS";
export const EXPLANATION_LIST_FAIL = "EXPLANATION_LIST_FAIL";

export const EXPLANATION_TOPICS_LIST_REQUEST =
  "EXPLANATION_TOPICS_LIST_REQUEST";
export const EXPLANATION_TOPICS_LIST_SUCCESS =
  "EXPLANATION_TOPICS_LIST_SUCCESS";
export const EXPLANATION_TOPICS_LIST_FAIL = "EXPLANATION_TOPICS_LIST_FAIL";


export const EXPLANATION_TOPIC_DETAIL_LIST_REQUEST = "EXPLANATION_TOPIC_DETAIL_LIST_REQUEST";
export const EXPLANATION_TOPIC_DETAIL_LIST_SUCCESS =  "EXPLANATION_TOPIC_DETAIL_LIST_SUCCESS";
export const EXPLANATION_TOPIC_DETAIL_LIST_FAIL = "EXPLANATION_TOPIC_DETAIL_LIST_FAIL";

export const SECTION_LIST_REQUEST = "SECTION_LIST_REQUEST";
export const SECTION_LIST_SUCCESS = "SECTION_LIST_SUCCESS";
export const SECTION_LIST_FAIL = "SECTION_LIST_FAIL";

export const QUESTION_LIST_REQUEST = "QUESTION_LIST_REQUEST";
export const QUESTION_LIST_SUCCESS = "QUESTION_LIST_SUCCESS";
export const QUESTION_LIST_FAIL = "QUESTION_LIST_FAIL";


export const QUESTION_DETAILS_REQUEST = "QUESTION_DETAIL_REQUEST";
export const QUESTION_DETAILS_SUCCESS = "QUESTION_DETAIL_SUCCESS";
export const QUESTION_DETAILS_FAIL = "QUESTION_DETAIL_FAIL";


export const QUESTION_REVIEW_CREATE_REQUEST = "QUESTION_REVIEW_CREATE_REQUEST";
export const QUESTION_REVIEW_CREATE_SUCCESS = "QUESTION_REVIEW_CREATE_SUCCESS";
export const QUESTION_REVIEW_CREATE_FAIL = "QUESTION_REVIEW_CREATE_FAIL";
export const QUESTION_REVIEW_CREATE_RESET = "QUESTION_REVIEW_CREATE_RESET";

export const EXPLANATION_DETAILS_REQUEST = "EXPLANATION_DETAILS_REQUEST";
export const EXPLANATION_DETAILS_SUCCESS = "EXPLANATION_DETAILS_SUCCESS";
export const EXPLANATION_DETAILS_FAIL = "EXPLANATION_DETAILS_FAIL";

export const EXPLANATION_CREATE_REQUEST = "EXPLANATION_CREATE_REQUEST";
export const EXPLANATION_CREATE_SUCCESS = "EXPLANATION_CREATE_SUCCESS";
export const EXPLANATION_CREATE_FAIL = "EXPLANATION_CREATE_FAIL";
export const EXPLANATION_CREATE_RESET = "EXPLANATION_CREATE_RESET";

export const EXPLANATION_UPDATE_REQUEST = "EXPLANATION_UPDATE_REQUEST";
export const EXPLANATION_UPDATE_SUCCESS = "EXPLANATION_UPDATE_SUCCESS";
export const EXPLANATION_UPDATE_FAIL = "EXPLANATION_UPDATE_FAIL";
export const EXPLANATION_UPDATE_RESET = "EXPLANATION_UPDATE_RESET";

export const EXPLANATION_DELETE_REQUEST = "EXPLANATION_DELETE_REQUEST";
export const EXPLANATION_DELETE_SUCCESS = "EXPLANATION_DELETE_SUCCESS";
export const EXPLANATION_DELETE_FAIL = "EXPLANATION_DELETE_FAIL";
export const EXPLANATION_DELETE_RESET = "EXPLANATION_DELETE_RESET";

export const EXPLANATION_CATEGORY_LIST_SUCCESS =
  "EXPLANATION_CATEGORY_LIST_SUCCESS";
export const EXPLANATION_CATEGORY_LIST_REQUEST =
  "EXPLANATION_CATEGORY_LIST_REQUEST";
export const EXPLANATION_CATEGORY_LIST_FAIL = "EXPLANATION_CATEGORY_LIST_FAIL";
